/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigWrap: typeof import('./src/custom-platform/ConfigWrap.vue')['default']
    Control: typeof import('./src/custom-platform/control/index.vue')['default']
    ControlNestWidget: typeof import('./src/custom-platform/control/ControlNestWidget.vue')['default']
    CustomPlatform: typeof import('./src/custom-platform/index.vue')['default']
    NavBar: typeof import('./src/custom-platform/navBar/index.vue')['default']
    PageConfig: typeof import('./src/custom-platform/pageConfig/index.vue')['default']
    PreviewModal: typeof import('./src/custom-platform/navBar/previewModal.vue')['default']
    WidgetShape: typeof import('./src/custom-platform/control/WidgetShape.vue')['default']
  }
}
