/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AColorPicker: typeof import('@arco-design/web-vue')['ColorPicker']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
  }
}
